apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "promtable.name" . }}
    chart: {{ template "promtable.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "promtable.fullname" . }}

  annotations:
{{- if .Values.metric.enable }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
{{- end }}
{{- with .Values.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  minReadySeconds: 30
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "promtable.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.deploymentStrategy }}
  {{- if ne .Values.deploymentStrategy "RollingUpdate" }}
    rollingUpdate: null
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ template "promtable.name" . }}
        release: {{ .Release.Name }}
{{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      containers:
      - args:
        - --bigtable.project_id={{ required "bigtable.project_id is required" .Values.bigtable.project_id }}
        - --ensure-tables={{ .Values.ensure_tables }}
        - --bigtable.table_prefix={{ required "bigtable.table_prefix is required" .Values.bigtable.table_prefix }}
        - --bigtable.instance={{ required "bigtable.instance is required" .Values.bigtable.instance }}
        name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        ports:
        - containerPort: 9202
          name: http
          protocol: TCP
{{- if .Values.metric.enable -}}
        - containerPort: 9100
          name: prometheus
          protocol: TCP
{{- end -}}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 300

