apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "promtable.name" . }}
    chart: {{ template "promtable.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "promtable.fullname" . }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  minReadySeconds: 30
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "promtable.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.deploymentStrategy }}
  {{- if ne .Values.deploymentStrategy "RollingUpdate" }}
    rollingUpdate: null
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ template "promtable.name" . }}
        release: {{ .Release.Name }}
      annotations:
{{- if .Values.metric.enable }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"
{{- end }}
{{- with .Values.podAnnotations }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      containers:
      - args:
        - --bigtable.project_id={{ required "bigtable.project_id is required" .Values.bigtable.project_id }}
        - --bigtable.table_prefix={{ required "bigtable.table_prefix is required" .Values.bigtable.table_prefix }}
        - --bigtable.instance={{ required "bigtable.instance is required" .Values.bigtable.instance }}
        - --bigtable.expiration={{ .Values.bigtable.expiration }}
        - --ensure-tables={{ .Values.ensure_tables }}
        - --metric.enable={{ default "false" .Values.metric.enable }}
        - --hash-metric-name={{ default "false" .Values.hash_metric_rows }}
        - --enable-longterm-storage={{ default "false" .Values.enable_longterm_storage }}
{{- if .Values.enable_longterm_storage }}
        - --longterm_bigtable.project_id={{ required "longterm_bigtable.project_id is required" .Values.longterm_bigtable.project_id }}
        - --longterm_bigtable.table_prefix={{ required "longterm_bigtable.table_prefix is required" .Values.longterm_bigtable.table_prefix }}
        - --longterm_bigtable.instance={{ required "longterm_bigtable.instance is required" .Values.longterm_bigtable.instance }}
        - --longterm_bigtable.expiration={{ .Values.longterm_bigtable.expiration }}
{{- end }}
        name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        ports:
          - containerPort: 9202
            name: http
            protocol: TCP
{{- if .Values.metric.enable }}
          - containerPort: 9100
            name: prometheus
            protocol: TCP
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 300

