steps:
- name: 'google/cloud-sdk:alpine'
  entrypoint: sh
  args:
  - '-c'
  - |
    apk --update add tar ca-certificates curl bash; \
    mkdir -p /tmp; \
    curl --keepalive-time 2 -fLsSv --retry 20 -Y 100000 -y 60 -o /tmp/$helm-v2.12.0-linux-amd64.tar.gz https://storage.googleapis.com/kubernetes-helm/$helm-v2.12.0-linux-amd64.tar.gz; \
    tar -xvzf /tmp/$helm-v2.12.0-linux-amd64.tar.gz -C /tmp; \
    mv /tmp/linux-amd64/helm /bin/helm; \
    rm -rf /tmp; \
    helm init --client-only; \
    ./scripts/helm-package.sh --sync-repo
